// Fetch predictions from static JSON file (generated by notebook 4)
export const interpolationBase = '/.netlify/functions/api?type=interpolation';

export async function fetchPredictions() {
  try {
    const res = await fetch('/predictions.json');
    if (!res.ok) {
      console.warn(
        'Predictions not available. Make sure:',
        '\n1. Notebook 4 has been run to generate predictions',
        '\n2. predictions.json has been deployed to Netlify',
      );
      return [];
    }
    const data = await res.json();
    return Array.isArray(data) ? data : [];
  } catch (err) {
    console.warn('Predictions fetch failed:', err.message);
    return [];
  }
}

export async function fetchSensorData(sensorId) {
  try {
    const res = await fetch(`/.netlify/functions/api?sensor=${sensorId}`);
    if (!res.ok) {
      throw new Error('Failed to fetch sensor data');
    }
    return await res.json();
  } catch (err) {
    console.error(`Error fetching sensor ${sensorId}:`, err);
    return null;
  }
}
